config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  resources :flights
  resources :bookings
  resources :airports
  resources :users
  get "about" => "welcome#about"
  get "login" => "sessions#login"
  post "attempt_login" => "sessions#attempt_login"
  get "logout" => "sessions#logout"
  get "past_bookings" => "bookings#past"
  get "search_booking" => "bookings#search"
end

app/views/shared/_user_profile.html.erb
<% if session[:user_id] %>
  <% @user = User.find(session[:user_id]) %>
  <div class="col-md-6">
    <table>
      <thead>
        <tr>
          <th colspan="2"> Your User Profile </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Title:</td>
          <td><%= @user.title %></td>
        </tr>
        <tr>
          <td>Firstname:</td>
          <td><%= @user.firstname %></td>
        </tr>
        <tr>
          <td> Lastname:</td>
            <td><%= @user.lastname %></td>
        </tr>
        <tr>
          <td>Username:</td>
          <td><%= @user.username %></td>
        </tr>
        <tr>
          <td>Email:</td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td>Telephone:</td>
          <td><%= @user.telephone %></td>
        </tr>
      </tbody>
    </table><br>
    <div class="col-md-6">
      <%= link_to "View All My Bookings", past_bookings_path %><br>
      <%= link_to "View All Appifly Bookings", bookings_path if session[:admin_user_id] %>
    </div>
  </div>
<% else %>
  <div class="col-md-6">
    <div class="bootstrap-demo">
      <div class="card">
        <div class="card-block width"> 
          <h3 class="card-title">Notice: You are not signed in</h3>
          <h5 class="card-text">Once you create your booking you will not be able to make changes to it afterwards. You would still be able to view it though. Please <b><%= link_to "sign in", login_path %></b> or <b><%= link_to "create an account" %></b> so you can manage your bookings when you desire. </h5>
          <h5>If you prefer booking anonymously please continue below.</h5>
        </div>
      </div>
    </div>
  </div>
<% end %>