config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  resources :flights
  resources :bookings
  resources :airports
  resources :users
  get "about" => "welcome#about"
  get "login" => "sessions#login"
  post "attempt_login" => "sessions#attempt_login"
  get "logout" => "sessions#logout"
  get "past_bookings" => "bookings#past"
  get "search_booking" => "bookings#search"
end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :flights, dependent: :destroy
  validates_presence_of :name,
                        :continent,
                        :country,
                        :jurisdiction,
                        :state_and_code,
                        :rating
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  include Concerns::MessagesHelper

  before_action :verify_admin_login
  before_action :set_airport, only: [:show, :edit, :update, :destroy]

  def index
    @airports = Airport.all.paginate(page: params[:page], per_page: 30)
  end

  def new
    @airport = Airport.new
  end

  def create
    @airport = Airport.new(airport_params)
    if @airport.save
      redirect_to @airport, notice: airport_created_message
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @airport.update(airport_params)
      redirect_to @airport, notice: airport_updated_message
    else
      render :edit
    end
  end

  def destroy
    @airport.destroy
    redirect_to airports_url, notice: airport_removed_message
  end

  private

  def set_airport
    @airport = Airport.find_by(id: params[:id])
  end

  def airport_params
    params.require(:airport).permit(
      :name,
      :continent,
      :country,
      :jurisdiction,
      :state_and_code,
      :rating
    )
  end
end

app/views/airports/_form.html.erb
<div class="col-md-12">
  <div class="col-md-4">
    <%= bootstrap_form_for(@airport) do |f| %>
      <% if @airport.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@airport.errors.count, "error") %> prohibited this airport from being saved:</h2>

          <ul>
          <% @airport.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.text_field :name, required: true %>
      <%= f.text_field :jurisdiction, required: true %>
      <%= f.text_field :state_and_code, required: true %>
      <%= f.text_field :country, required: true %>
      <%= f.text_field :continent, required: true %>
      <%= f.text_field :rating, required: true %><br>
      <%= f.submit %>
    <% end %><br>
  </div>
</div>

app/views/airports/edit.html.erb
<h1>Editing Airport</h1>

<%= render "form" %>

<%= link_to "Cancel Editing", @airport %> |
<%= link_to "Back To Airport List", airports_path %>

app/views/airports/index.html.erb
<h1>Listing Airports</h1>
<%= will_paginate @airports, renderer: BootstrapPagination::Rails  %>
<table class="table">
  <thead>
    <tr>
      <th>Index</th>
      <th>Airport Name</th>
      <th>Jurisdiction</th>
      <th>State (Code)</th>
      <th>Country</th>
      <th>Continent</th>
      <th>Rating</th>
      <th colspan="3">Admin Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @airports.each_with_index do |airport, index| %>
      <tr>
        <td><%= index_for_pagination(index) %></td>
        <td><%= airport.name %></td>
        <td><%= airport.jurisdiction %></td>
        <td><%= airport.state_and_code %></td>
        <td><%= airport.country %></td>
        <td><%= airport.continent %></td>
        <td><%= airport.rating %></td>
        <td><%= link_to "Show", airport %></td>
        <td><%= link_to "Edit", edit_airport_path(airport) %></td>
        <td><%= link_to "Remove", airport, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @airports, renderer: BootstrapPagination::Rails  %>

<br>

<%= link_to "Create New Airport", new_airport_path %>

app/views/airports/new.html.erb
<h1>New Airport</h1>

<%= render "form" %>

<%= link_to "Back To Airport List", airports_path %>

app/views/airports/show.html.erb
<h3>
  <strong><%= @airport.name %></strong>
</h3>

<p>
  <strong>Jurisdiction:</strong>
  <%= @airport.jurisdiction %>
</p>

<p>
  <strong>State (Code):</strong>
  <%= @airport.state_and_code %>
</p>

<p>
  <strong>Country:</strong>
  <%= @airport.country %>
</p>

<p>
  <strong>Continent:</strong>
  <%= @airport.continent %>
</p>

<p>
  <strong>Airport Rating:</strong>
  <%= @airport.rating %>
</p>

<%= link_to "Edit This Airport", edit_airport_path(@airport) %> |
<%= link_to "Back To Airport List", airports_path %>