config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  resources :flights
  resources :bookings
  resources :airports
  resources :users
  get "about" => "welcome#about"
  get "login" => "sessions#login"
  post "attempt_login" => "sessions#attempt_login"
  get "logout" => "sessions#logout"
  get "past_bookings" => "bookings#past"
  get "search_booking" => "bookings#search"
end

app/views/layouts/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
      </button>
      <%= link_to "Appifly", root_path, class: "navbar-brand page-scroll" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Find Your Booking", search_booking_path %>
        </li>
        <% if session[:user_id] %>
          <li>
            <%= link_to "Manage Bookings", past_bookings_path %> 
          </li>
          <li>
            <%= link_to "Sign out", "/logout" %> 
          </li>
          <li class="signed_in">
            Signed in as <%=session[:user_username] %> 
            <%= "**" if session[:admin_user_id] %>
          </li>
        <% else %>
          <li>
            <%= link_to "Sign in", login_path %>
          </li>
          <li>
            <%= link_to "Sign up", new_user_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appifly</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render "layouts/navbar" %>
      <div class="header-nav"></div>
      <%= "<p id='notice'>#{notice}</p>".html_safe if notice %>
      <%= "<p id='alert'>#{alert}</p>".html_safe if alert %>
      <div class="container">
        <div class="row heading-row">
      <%= yield %>
        </div>
      </div>
    </header>
    <footer>
      <div class="container">
        <p>&copy; Appifly. All Rights Reserved.</p>
        <ul class="list-inline">
          <li>
            <a href="#">Privacy</a>
          </li>
          <li>
            <a href="#">Terms</a>
          </li>
          <li>
            <a href="#">FAQ</a>
          </li>
        </ul>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/welcome_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appifly</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render "layouts/navbar" %>
      <div class="header-nav"></div>
      <%= "<p id='notice'>#{notice}</p>".html_safe if notice %>
      <%= "<p id='alert'>#{alert}</p>".html_safe if alert %>
      <%= yield %>
    </header>
    <footer>
      <div class="container">
        <p>&copy; Appifly. All Rights Reserved.</p>
        <ul class="list-inline">
          <li>
            <a href="#">Privacy</a>
          </li>
          <li>
            <a href="#">Terms</a>
          </li>
          <li>
            <a href="#">FAQ</a>
          </li>
        </ul>
      </div>
    </footer>
  </body>
</html>